spring:
  application:
    name: zuul-server
server:
  port : 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://52.39.158.79:8761/eureka/
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://52.39.158.79:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://52.39.158.79:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://52.39.158.79:1003
    cart:
      path: /cart/**
      url: http://52.39.158.79:1004/api/v1
    shoe-service:
      path: /shoeapi/**
      serviceId: shoe-client
    offer-service:
      path: /offerapi/**
      serviceId: offers-client
    cart-service:
      path: /cartapi/**
      serviceId: cart-client
